services:
  db:
    image: postgis/postgis:16-3.4
    container_name: paws_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: paws_and_found
      POSTGRES_USER: paws_admin
      POSTGRES_PASSWORD: swacdevs2026
    ports:
      - "5432:5432"
    volumes:
      - paws_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paws_admin -d paws_and_found"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paws_backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  paws_pgdata: