# Generated by Django 5.0.14 on 2026-09-26 12:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=255)),
                ('distinguishingMarks', models.TextField(blank=True, null=True)),
                ('photoURLs', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('featureVector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('lastKnownLocation', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.CharField(choices=[('Missing', 'Missing'), ('Recovered', 'Recovered')], default='Missing', max_length=20)),
                ('dateReported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animalType', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photoURL', models.URLField()),
                ('featureVector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.CharField(choices=[('Stray', 'Stray'), ('Missing', 'Missing'), ('Found', 'Found')], default='Stray', max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabaseUserID', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=32, null=True)),
                ('profilePhotoURL', models.URLField(blank=True, null=True)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarityScore', models.FloatField()),
                ('distanceKM', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('dateGenerated', models.DateTimeField(auto_now_add=True)),
                ('petID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.pet')),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='reporterUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.user'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ownerUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MatchFound', 'MatchFound'), ('ReportUpdate', 'ReportUpdate'), ('VerificationRequest', 'VerificationRequest'), ('MatchConfirmed', 'MatchConfirmed')], max_length=30)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('relatedMatchID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.match')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user')),
            ],
        ),
    ]
